package minigmail;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

public class MiniGmail extends javax.swing.JFrame {

    Random r = new Random();

    /**
     * Creates new form MiniGmail
     */
    public MiniGmail() {
        initComponents();

        jPanel1.setBackground(new Color(r.nextInt(255) + 1, r.nextInt(255) + 1, r.nextInt(255) + 1));
        cargarCuentas();

        this.setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
        //bt_signIn

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_ingreso = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        bt_login = new javax.swing.JButton();
        cb_ingreso_cuentas = new javax.swing.JComboBox<>();
        pf_ingreso_clave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        bt_signIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menu_bar = new javax.swing.JMenuBar();
        jm_admin = new javax.swing.JMenu();

        jd_ingreso.setTitle("Ingreso");
        jd_ingreso.setAlwaysOnTop(true);
        jd_ingreso.setResizable(false);
        jd_ingreso.setSize(new java.awt.Dimension(392, 300));
        jd_ingreso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jd_ingresoFocusLost(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        bt_login.setText("Ingresar");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        cb_ingreso_cuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jButton1.setText("Crear una cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_login, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ingreso_cuentas, 0, 184, Short.MAX_VALUE)
                    .addComponent(pf_ingreso_clave))
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(cb_ingreso_cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pf_ingreso_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_login)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_ingresoLayout = new javax.swing.GroupLayout(jd_ingreso.getContentPane());
        jd_ingreso.getContentPane().setLayout(jd_ingresoLayout);
        jd_ingresoLayout.setHorizontalGroup(
            jd_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd_ingresoLayout.setVerticalGroup(
            jd_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 10));
        setSize(new java.awt.Dimension(900, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));

        bt_signIn.setBackground(new java.awt.Color(0, 0, 255));
        bt_signIn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_signIn.setForeground(new java.awt.Color(255, 255, 255));
        bt_signIn.setText("SIGN IN");
        bt_signIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_signIn.setBorderPainted(false);
        bt_signIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_signIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_signInActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Personalizar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(bt_signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396))
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addGap(421, 421, 421)
                    .addComponent(jLabel1)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(bt_signIn)
                .addGap(362, 362, 362))
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addGap(294, 294, 294)
                    .addComponent(jLabel1)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );

        menu_bar.setBorderPainted(false);
        menu_bar.setEnabled(false);

        jm_admin.setText("Administración");
        menu_bar.add(jm_admin);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        if (jd_ingreso.isVisible()) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_formWindowDeiconified

    private void bt_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_signInActionPerformed
        jd_ingreso.setLocationRelativeTo(this);
        jd_ingreso.pack();
        //jd_ingreso.setModal(true);
        //jd_ingreso.setAlwaysOnTop(true);
        jd_ingreso.setVisible(true);
    }//GEN-LAST:event_bt_signInActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        if (cb_ingreso_cuentas.getSelectedIndex() >= 0) {

            String pass = ((Cuenta) cb_ingreso_cuentas.getSelectedItem()).getClave();
            try {
                if (pf_ingreso_clave.getText().equals(pass)) {
                    JOptionPane.showMessageDialog(jd_ingreso, "Ingreso exitoso.", "Ingresado", JOptionPane.INFORMATION_MESSAGE);
                    
                    panel.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(jd_ingreso, "La contraseña ingresada es incorrecta.", "No ingresado", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "Debe ingresar una contraseña.", "Contraseña no ingresada", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_bt_loginActionPerformed

    private void jd_ingresoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jd_ingresoFocusLost
        
    }//GEN-LAST:event_jd_ingresoFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        panel.setBackground(
                JColorChooser.showDialog(this, "Elija un color de fondo", Color.red)
        );
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cargarCuentas() {
        File file = new File("./Users.txt");

        if (file.exists()) {

            FileReader fr = null;
            BufferedReader br = null;
            try {

                DefaultComboBoxModel model = (DefaultComboBoxModel) cb_ingreso_cuentas.getModel();

                fr = new FileReader(file);
                br = new BufferedReader(fr);

                String line = "";
                while ((line = br.readLine()) != null) {

                    String[] palabras = line.split(";");
                    Cuenta c = new Cuenta();
                    c.setdireccionCorreoElectronico(palabras[0]);
                    c.setClave(palabras[1]);

                    model.addElement(c);

                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MiniGmail.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MiniGmail.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    br.close();
                    fr.close();
                } catch (IOException ex) {
                    Logger.getLogger(MiniGmail.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniGmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniGmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniGmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniGmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniGmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_signIn;
    private javax.swing.JComboBox<String> cb_ingreso_cuentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDialog jd_ingreso;
    private javax.swing.JMenu jm_admin;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField pf_ingreso_clave;
    // End of variables declaration//GEN-END:variables
}
